# Generated by Django 4.2.6 on 2023-11-10 17:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_profilo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='user_profile'),
        ),
    ]
