# Generated by Django 4.2.6 on 2023-11-16 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_img_profilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Puoi inserire solo 5 numeri', regex='^[0-9]{4,5}$')], verbose_name='C.A.P.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comune',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comune'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Indirizzo'),
        ),
    ]
