# Generated by Django 4.2.6 on 2023-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'main_category')},
        ),
    ]
